#pragma once


enum UnitType {
	HUMAN_WITH_SWORD, HUMAN_WITH_BAT, HUMAN_WITH_GUN, HUMAN_WITH_GRENADE, HUMAN_ON_CAR, HUMAN_ON_BIKE, BITING_ZOMBY, STINKY_ZOMBY, SPIT_TO_ENEMY_ZOMBY, SPIT_TO_AREA_ZOMBY, STRONG_ZOMBY, KAMIKADZE_ZOMBY
};