#include "isoscelesTriangle.h"
#include "rightTriangle.h"
#include "square.h"
#include <iostream>
#include <vector>

int main()
{
	Point p_1(1,1);
	Point p_2(2,2); 
	Point p_3(1,3);
	Point p_4(4,5);
	std::cout << "Создаем треугольник tr_1: " << std::endl;
	Triangle tr_1(p_1, p_2, p_3, "FF", "FF", "FF");
	std::cout << tr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Копируем его в tr_2: " << std::endl;
	Triangle tr_2(tr_1);
	std::cout << tr_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Поворачиваем tr_2 на 60 градусов: " << std::endl;
	tr_2.rotate(60);
	std::cout << tr_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;	
	std::cout << "Масштабируем в 1.5 раз: " << std::endl;
	tr_2.scale(1.5);
	std::cout << tr_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Сдвигаем на (5,5)" << std::endl;
	Point move_1(5,5);
	tr_2.move(move_1);
	std::cout << tr_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "-----------------------------------------------" << std::endl << std::endl;
	std::cout << "Создаем квадрат sq: " << std::endl;
	Square sq(p_1, 4, "11", "01", "11");
	std::cout << sq << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "sq_2 = sq " << std::endl;
	Square sq_2 = sq;
	std::cout << sq_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Поворачиваем sq_2 на 90 градусов: " << std::endl;
	sq_2.rotate(90);
	std::cout << sq_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;	
	std::cout << "Масштабируем в 3 раз: " << std::endl;
	sq_2.scale(3);
	std::cout << sq_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Сдвигаем на (2,-2)" << std::endl;
	Point move_2(2,-2);
	sq_2.move(move_2);
	std::cout << sq_2 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "-----------------------------------------------" << std::endl << std::endl;
	std::cout << "Создаем равнобедренный треугольник itr_1: " << std::endl;
	IsoscelesTriangle itr_1(p_1, 30, 6, "FF", "FF", "FF");
	std::cout << itr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Поворачиваем itr_1 на 0 градусов: " << std::endl;
	itr_1.rotate(0);
	std::cout << itr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;	
	std::cout << "Масштабируем в 0.5 раз: " << std::endl;
	itr_1.scale(0.5);
	std::cout << itr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Сдвигаем на (1,1)" << std::endl;
	Point move_3(1,1);
	itr_1.move(move_3);
	std::cout << itr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "-----------------------------------------------" << std::endl << std::endl;
	std::cout << "Создаем прямоугольный треугольник rtr_1: " << std::endl;
	RightTriangle rtr_1(p_1, 3, 4, "FF", "FF", "FF");
	std::cout << rtr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Поворачиваем rtr_1 на 360 градусов: " << std::endl;
	rtr_1.rotate(360);
	std::cout << rtr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;	
	std::cout << "Масштабируем в 2 раз: " << std::endl;
	rtr_1.scale(2);
	std::cout << rtr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Сдвигаем на (-1,-1)" << std::endl;
	Point move_4(-1, -1);
	rtr_1.move(move_4);
	std::cout << rtr_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "-----------------------------------------------" << std::endl << std::endl;
	std::cout << "Создаем прямоугольник r_1: " << std::endl;
	Rectangle r_1(p_1, 3, 4, "0F", "0F", "0F");
	std::cout << r_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Поворачиваем r_1 на 270 градусов: " << std::endl;
	r_1.rotate(270);
	std::cout << r_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;	
	std::cout << "Масштабируем в 2 раз: " << std::endl;
	r_1.scale(2);
	std::cout << r_1 << std::endl;
	std::cout << "-----------------------------------------------" << std::endl;
	std::cout << "Сдвигаем на (10,-10)" << std::endl;
	Point move_5(-10, -10);
	r_1.move(move_5);
	std::cout << r_1 << std::endl;
}