var searchData=
[
  ['scopedprematureexitfile_985',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1_scoped_premature_exit_file.html',1,'testing::internal']]],
  ['scopedtrace_986',['ScopedTrace',['../classtesting_1_1_scoped_trace.html',1,'testing']]],
  ['separateinstancetest_987',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequencetestinglistener_988',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['setargumentpointeeaction_989',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['seterrnoandreturnaction_990',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setup_5fshould_5fbe_5fspelled_5fsetup_991',['Setup_should_be_spelled_SetUp',['../structtesting_1_1_test_1_1_setup__should__be__spelled___set_up.html',1,'testing::Test::Setup_should_be_spelled_SetUp'],['../structtesting_1_1_environment_1_1_setup__should__be__spelled___set_up.html',1,'testing::Environment::Setup_should_be_spelled_SetUp']]],
  ['setupenvironment_992',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_993',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_994',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuitetest_995',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['sink_996',['Sink',['../structtesting_1_1internal_1_1_ignored_value_1_1_sink.html',1,'testing::internal::IgnoredValue']]],
  ['skipentireenvironmenttest_997',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skippedtest_998',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['stackinterface_999',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['state_1000',['State',['../structtesting_1_1internal_1_1_return_round_robin_action_1_1_state.html',1,'testing::internal::ReturnRoundRobinAction']]],
  ['statefulnamingfunctor_1001',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_1002',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['staticasserttypeeqtesthelper_1003',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['stlcontainerview_1004',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_1005',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_1006',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['streamableinglobal_1007',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamabletemplateinfoo_1008',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['strictmock_1009',['StrictMock',['../classtesting_1_1_strict_mock.html',1,'testing']]],
  ['string_1010',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['stripmetacommentstest_1011',['StripMetaCommentsTest',['../classpump__test_1_1_strip_meta_comments_test.html',1,'pump_test']]],
  ['struct_1012',['Struct',['../classcpp_1_1ast_1_1_struct.html',1,'cpp::ast']]],
  ['subprocess_1013',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['subversionvcs_1014',['SubversionVCS',['../classupload_1_1_subversion_v_c_s.html',1,'upload']]],
  ['successfultest_1015',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['suiteapiresolver_1016',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['sumof5functor_1017',['SumOf5Functor',['../structtesting_1_1gmock__generated__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_generated_actions_test::SumOf5Functor'],['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test::SumOf5Functor']]],
  ['sumof6functor_1018',['SumOf6Functor',['../structtesting_1_1gmock__generated__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_generated_actions_test::SumOf6Functor'],['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test::SumOf6Functor']]]
];
